apiVersion: cert-manager.io/v1alpha2
Kind: Certificate
metadata:
  name: k8s-multi-com-tls
spec:
  secretName: k8s-multi-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: parkyes90.dev
  dnsNames:
    - parkyes90.dev
    - www.parkyes90.dev
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - parkyes90.dev
          - www.parkyes90.dev
